# -*- coding: utf-8 -*-
"""spam detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PsGC0G7Sr_d4tc7AY6LdJHOMM5XMOnoV
"""

import numpy as np
import pandas as pd
import seaborn as sbs

df=pd.read_csv("/content/emails.csv")
df.head()

df=df.iloc[:,:2]
df

df.info()

df.shape

df.isna().sum()

df.drop_duplicates(inplace=True)

df.dropna(inplace=True)

df.isnull().sum()

df.isnull().values.any()

df.spam.value_counts()

df.shape

x=df['text']
y=df['spam']

x.head()

y

from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
x=cv.fit_transform(x)

x.toarray()

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

from sklearn.naive_bayes import MultinomialNB
gnb=MultinomialNB()
gnb.fit(x_train,y_train)

gnb.score(x_test,y_test)

from sklearn.naive_bayes import BernoulliNB
bnb=BernoulliNB()
bnb.fit(x_train,y_train)

bnb.score(x_test,y_test)

new_emails = ['WINNER!! As a valued network customer you have been selected to receivea Â£900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.']
X_IN = cv.transform(new_emails)
y_OUT = gnb.predict(X_IN)

from google.colab import drive
drive.mount('/content/drive')

print(y_OUT)

for i in y_OUT:
  if i=='1':
    print("SPAM")
  else:
    print("NOT_SPAM")
    